name: inception

secrets:
  mariadb_root_pw:
    file: secrets/mariadb_root_pw.txt
  mariadb_user_pw:
    file: secrets/mariadb_user_pw.txt
  wp_admin_pw:
    file: secrets/wp_admin_pw.txt
  wp_user_pw:
    file: secrets/wp_user_pw.txt

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/juaho/data/mariadb_data
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/juaho/data/wordpress_data

services:
  nginx:
    image: nginx
    container_name: nginx
    init: true
    restart: unless-stopped
    build: requirements/nginx/.
    volumes:
      - wp_data:/www
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"

  wordpress:
    image: wordpress
    container_name: wordpress
    init: true
    restart: unless-stopped
    build: requirements/wordpress/.
    volumes:
      - wp_data:/www
    env_file: "./.env"
    healthcheck:
      test: [ "CMD-SHELL", "pgrep php-fpm || exit1" ]
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 110s
    depends_on:
      mariadb:
        condition: service_healthy
    secrets:
      - mariadb_user_pw
      - wp_admin_pw
      - wp_user_pw

  mariadb:
    image: mariadb
    container_name: mariadb
    init: true
    restart: unless-stopped
    build: requirements/mariadb/.
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: "./.env"
    healthcheck:
      test: ["CMD", "mariadb-admin",  "-uhealthcheck", "ping", "-h", "localhost", "--protocol=tcp"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s
    secrets:
      - mariadb_root_pw
      - mariadb_user_pw
